# Generated by Django 3.0.8 on 2020-07-24 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_hora_extra', '0003_horaextra_horas'),
    ]

    operations = [
        migrations.AddField(
            model_name='horaextra',
            name='utilizadas',
            field=models.BooleanField(default=False),
        ),
    ]
