# Generated by Django 3.0.8 on 2020-07-25 20:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_hora_extra', '0004_horaextra_utilizadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='horaextra',
            name='criada_em',
            field=models.DateField(default=datetime.datetime(2020, 7, 25, 17, 0, 31, 699524)),
        ),
    ]
