# Generated by Django 3.0.8 on 2020-07-25 20:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('registro_hora_extra', '0005_horaextra_criada_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horaextra',
            name='criada_em',
            field=models.DateField(default=datetime.datetime(2020, 7, 25, 20, 1, 27, 976396, tzinfo=utc)),
        ),
    ]
