# Generated by Django 3.0.8 on 2020-07-26 16:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registro_hora_extra', '0008_auto_20200726_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horaextra',
            name='criada_em',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
