# Generated by Django 3.0.8 on 2020-07-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0002_departamento_empresa'),
        ('funcionario', '0004_auto_20200718_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='departamentos',
            field=models.ManyToManyField(blank=True, null=True, to='departamento.Departamento'),
        ),
    ]
