# Generated by Django 3.0.8 on 2020-07-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0005_auto_20200719_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='imagem',
            field=models.ImageField(default=0, upload_to='fotos'),
            preserve_default=False,
        ),
    ]
