# Generated by Django 3.0.8 on 2020-07-26 16:43

from django.db import migrations, models
import gestao_rh.apps.funcionario.models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0002_departamento_empresa'),
        ('funcionario', '0006_funcionario_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='departamentos',
            field=models.ManyToManyField(blank=True, to='departamento.Departamento'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='imagem',
            field=models.ImageField(upload_to=gestao_rh.apps.funcionario.models.user_directory_path),
        ),
    ]
